apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: nicedoc.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-{{ .Release.Name }}
          servicePort: 3000
